services:
  image-engine:
    build: .
    image: image-engine
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
